version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
      - '5858:5858'
    container_name: timmywil
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.yarn
